
  #--- 
  #apiVersion: networking.k8s.io/v1
  #kind: Ingress
  #metadata:
  #  name: dev-ingress
  #  namespace: dev
  #spec:
  #  rules:
  #  - http:
  #      paths:
  #      - pathType: Prefix
  #        path: /
  #        backend:
  #          service:
  #            name: will
  #            port:
  #              number: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: will
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 8888 # Port exposed within the cluster
      targetPort: 8888 # Port on the pods
      nodePort: 30000 # Port accessible externally on each node
  selector:
    app: will # Select pods with this label

---
apiVersion: v1
kind: Endpoints
metadata:
  name: whatami
  namespace: dev
subsets:
- addresses:
  - ip: 10.42.0.18
    nodeName: k3d-p3-server-0
    targetRef:
      kind: Pod
      name: will-c48dfb996-j5q48
      namespace: dev
      uid: 8688703d-3109-496b-ba84-b7656171208e
  - ip: 10.42.0.19
    nodeName: k3d-p3-server-0
    targetRef:
      kind: Pod
      name: will-c48dfb996-pmqnb
      namespace: dev
      uid: c3bdf355-4d8f-44e0-9802-3af4f9011123
  - ip: 10.42.0.20
    nodeName: k3d-p3-server-0
    targetRef:
      kind: Pod
      name: will-c48dfb996-t75ql
      namespace: dev
      uid: 80996cfe-aefb-4e22-adf9-330875285d84
  ports:
  - port: 8888
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: will
  namespace: dev
spec:
  selector:
    matchLabels:
      app: will
  replicas: 3
  template:
    metadata:
      labels:
        app: will
    spec:
      containers:
      - name: will
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
