
  #--- 
  #apiVersion: networking.k8s.io/v1
  #kind: Ingress
  #metadata:
  #  name: dev-ingress
  #  namespace: dev
  #spec:
  #  rules:
  #  - http:
  #      paths:
  #      - pathType: Prefix
  #        path: /
  #        backend:
  #          service:
  #            name: will
  #            port:
  #              number: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: will
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 8888 # Port exposed within the cluster
      targetPort: 8888 # Port on the pods
      nodePort: 30000 # Port accessible externally on each node
  selector:
    app: will # Select pods with this label

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: will
  namespace: dev
spec:
  selector:
    matchLabels:
      app: will
  replicas: 1
  template:
    metadata:
      labels:
        app: will
    spec:
      containers:
      - name: will
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
