name: Validate-YAML

# Source - https://stackoverflow.com/a/71335391
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML file
        run: yamllint *.yaml
  
  validate-will-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Accept only v1 or v2 of Will app
        run: grep 'wil42/playground:v1' dev.yaml || grep 'wil42/playground:v2' dev.yaml
